### ISSUE TITLE
d3.svg.multibrush in d3 V4 ?

### ISSUE THREAD

**Issue by Abhijeet-Das** [humanitiesplusdesign/d3.svg.multibrush#10]
Hello, 

As the brush functionality has changed in d3 V4, Could anyone please share the updated version of d3.svg.multibrush.js in d3 V4.  

I have been working on parallel coordinate with multiple brushes on an axis. The sample examples are in V3, but I am looking multiple brush in V4.

Thanks

**Comment by esjewett** [comment]
Hi - no plans at this time to update this to d3 V4. You are more than welcome to do so though. Sorry I can't be more of a help.
