### ISSUE TITLE
An example?

### ISSUE THREAD

**Issue by sepans** [humanitiesplusdesign/d3.svg.multibrush#4]
Could you please put a demo up?

**Comment by esjewett** [comment]
It's more or less a drop-in replacement for d3.svg.brush. We have a usage example in the Palladio timeline at https://github.com/humanitiesplusdesign/palladio/blob/master/src/components/palladio-timeline-filter/palladio-timeline-filter.js

**Comment by sepans** [comment]
Thanks for the link, though it is not more descriptive than the multibrush code itself. I want to add multiple range selection to each of these histograms in [this](http://lenses.github.io/lens-data-crossfilter/components/lens-data-crossfilter/demo.html) example but I am not sure multibrush does that. If thats the case I don't mind putting up adding a minimal exampe demo page to the library (as a PR) because the text description doesn't do justice to the power that this library could bring.

**Comment by esjewett** [comment]
Yes, it definitely can do that, though you would have to modify the filter code as the brush region will move from being a 2-element array to being an array of 2-element arrays. An example image of how it works in Palladio based on that file:

![screen shot 2015-04-23 at 5 34 12 pm](https://cloud.githubusercontent.com/assets/4822/7308966/0ba663f4-e9df-11e4-95d3-f5a7e3931aaa.png)

Is this what you have in mind?

Also, PRs are more than welcome! If you come up with a partial example and need some help, please just post a jsFiddle or similar example and update this issue. I'll be happy to take a look.

**Comment by sepans** [comment]
Thanks @esjewett . That is exactly it. And yes I also saw the difference in the extent method from regular brush.
